export const GENDERS = [
        "Male",
        "Female",
        "Non binary",
        "Transgender" ,
        "Genderqueer",
        "Cisgender",
        "Trans man",
        "Trans woman",
        "Agender",
        "Genderfluid",
        "Bigender",
        "Intersex",
        "Androgynous",
        "Demiboy",
        "Demigirl",
        "Genderflux",
        "Questioning",
        "Cis man",
        "FTM",
        "MTF",
        "Polygender",
        "Pangender",
        "Two Spirit",
        "nonconforming",
        "Transfeminine",
        "Transmasculine",
        "Androgyne",
        "Neutrois",
        "Abinary",
        "Aporagender",
        "Autigender",
        "Maverique ",
        "Trigender",
        "Hijra",
        "Butch",
        "Femme",
        "Agenderflux",
        "Bakla",
        "Bissu",
        "Calabai",
        "Calalai",
        "Demiflux",
        "Genderblank",
        "Genderfree",
        "Gender gifted",
        "Gender variant",
        "Graygender",
        "Intergender",
        "Ipsogender",
        "Kathoey",
        "Māhū",
        "Meta gender",
        "Muxe",
        "Omnigender",
        "Sekhet",
        "Third gender",
        "Transsexual",
        "Travesti",
        "Tumtum",
        "Vakasalewalewa",
        "Waria",
        "X gender",
        "X jendā",
        "Xenogender",
];