export const GENDER_BALLS_COLLECTION = 'gender-balls'
export const POLITICS_COLLECTION = 'politics'
export const LIVING_HERE_COLLECTION = 'living-here'
export const ICE_CREAM_SANDWICH_COLLECTION = 'ice-cream-sandwich'
export const NAME_COLLECTION = 'name'
export const SMILE = 'smile'